Prefix invalid subject values with a valid prefix
codeready-toolchain/registration-service pull request #165
Opened 2021-01-13 11:50 UTC by sbryzak

This PR fixes the signup process for users that have a subject (i.e. their RHD SSO UserID) claim that starts with a minus (-) symbol.  Since this prefix is invalid for use as a UserSignup resource name (as it is not DNS-1123 compliant) this PR will prefix the subject value with a hex representation of the CRC checksum of the initial value. 

For example, if the subject claim looks like this: `-2cf24956-7a5f-4115-88eb-1d95e0190359` then the registration service will now prefix it like so: `1b09f3a8-2cf24956-7a5f-4115-88eb-1d95e0190359`.  This new value will then be used for UserSignup.Name.

Fixes https://issues.redhat.com/browse/CRT-915

2021-01-13 15:01 UTC, MatousJobanek reviewed
Correct me if I'm wrong: by adding the prefix containing the hash that is counted using the reverse polynomial we will get the positive id (claim)...? How do we know that this will be accepted by SSO when we put this new ID into the identity in the member cluster?

2021-01-13 17:27 UTC, alexeykazakov requested changes
As Matous mentioned we can't just replace the actual User ID to something generated when creating UserSignup.
The UserSignup.Name is used to create User and Identity in member cluster (it's passed through MUR): https://github.com/codeready-toolchain/host-operator/blob/c97e93e04fd641af6e9d38d5ea4e470b2691e441/pkg/controller/usersignup/masteruserrecord.go#L71 
If we just code the name without decoding it before creating an actual user then the user won't be able to login because the User IDs won't match.

Also, have you seen my comments in https://issues.redhat.com/browse/CRT-915 ?
Right now we have an issue with IDs which start with `-`. But we plan to switch to regular sso clients (without sub claim override) and UserIDs will also contain `:` (we should support any sub claim with URI scheme, for example it may contain `/`).

So, I see two options here:
- refactor our UserSignup CRD to use a different approach rather then using UserID as the resource name so we can support URI scheme/names). It should solve that issue with `-` too.
- split https://issues.redhat.com/browse/CRT-915 to two issues:
   1) Add something for now to fix the `-` issue our users currently face
   2) Deep UserSignup refactoring to switch to a new approach to support URI scheme

If we split the issue then for the "quick" fix we could use some prefix in UserSignup.Name which we can easily recognize and decode to get the original User ID.
For the URI scheme issue we need to think more... If we could code the entire User ID to some DNS complaint name and decode it 100% correct for all User IDs then it would solve all our problems. If it's impossible then we will need to stop using User IDs as the resource names and come up with something else.

Also, regardless of what we do now we have to add e2e tests for the PR :)

2021-01-18 09:27 UTC, sbryzak commented on pkg/signup/service/signup_service.go
> +		return fmt.Sprintf("%x%s", crc32.Checksum([]byte(subject), crc32q), subject)
Thanks Matous, I wasn't aware of that shortcut.

2021-01-18 09:30 UTC, sbryzak commented
So this PR should now perform a one-way encoding of the user ID into a DNS-1123 compliant value.  With this change a number of further changes are required in the host operator, which are forthcoming.

2021-01-18 18:17 UTC, alexeykazakov reviewed
The encoding part looks good but let's add tests for `encodeUserID()` function with all possible combinations to cover that function 100%.

2021-01-20 23:33 UTC, alexeykazakov reviewed
Looks good overall. But please add more tests and fix the description.

2021-01-20 23:33 UTC, alexeykazakov commented on pkg/signup/service/signup_service.go
> +// EncodeUserID examines the first character of the specified subject value, and if invalid (i.e. it
It examines all the characters. Not just the first one. Doesn't it?

2021-01-20 23:33 UTC, alexeykazakov commented on pkg/signup/service/signup_service_test.go
> +		encoded := service.EncodeUserID(userID)
Please add more tests for different use cases. Such as `-something`, `something:something`, etc.

2021-01-20 23:33 UTC, alexeykazakov commented on pkg/signup/service/signup_service.go
> +			UserID:               ctx.GetString(context.SubKey),
Let's add a test which checks that Spec.UserID is set.

2021-01-20 23:41 UTC, sbryzak commented
> So this PR should now perform a one-way encoding of the user ID into a DNS-1123 compliant value. With this change a number of further changes are required in the host operator, which are forthcoming.

After further discussion with @alexeykazakov we're going to break up these changes into multiple PRs, as the order in which we do things here are actually quite important.  This PR simply now sets the new UserSignup.Spec.UserID.

2021-01-21 01:02 UTC, alexeykazakov approved these changes

2021-01-21 02:46 UTC, sbryzak commented
/retest

2021-01-21 04:30 UTC, merged