Lookup usersignup by username first then userid
codeready-toolchain/registration-service pull request #274
Opened 2022-07-17 21:01 UTC by sbryzak

This PR makes a small change to lookup the UserSignup by username first instead of userID

Fixes https://issues.redhat.com/browse/CRT-1570

2022-07-17 21:08 UTC, sbryzak commented
/retest

2022-07-18 09:52 UTC, MatousJobanek requested changes
As I mentioned in the comment - we need to fix all broken UserSignups first, then we can change the way we retrieve them.

2022-07-27 23:55 UTC, sbryzak commented on pkg/signup/service/signup_service.go
> +	userSignup, err := s.CRTClient().V1Alpha1().UserSignups().Get(EncodeUserIdentifier(username))
The analysis task has revealed that there are currently no UserSignups stuck in migration, so this is not a blocker.

2022-07-28 00:02 UTC, sbryzak commented on pkg/controller/signup_test.go
> +		require.Equal(s.T(), " \"\" not found: user not found", bodyParams["message"])
The error is correct, this is what's returned from the Kubernetes client which is passed back to the caller without modification.

2022-08-02 08:48 UTC, MatousJobanek commented on pkg/controller/signup_test.go
> +		require.Equal(s.T(), " \"\" not found: user not found", bodyParams["message"])
ok, I see why - at line 568 there is missing the username:
https://github.com/codeready-toolchain/registration-service/blob/2924c85484739aca7f778ed628d0271836f6fea4/pkg/controller/signup_test.go#L568
could you please fix that so it uses non-empty username?

2022-08-02 10:01 UTC, MatousJobanek approved these changes
Since there is no usersignup blocked in the migration process, then we should be fine with merging this PR. 
Just please fix the test that I mentioned in the comment https://github.com/codeready-toolchain/registration-service/pull/274#discussion_r935287038

2022-08-02 11:59 UTC, merged