Made UserSignup.Spec.IdentityClaims property required
codeready-toolchain/registration-service pull request #405
Opened 2024-02-26 23:01 UTC by sbryzak

Associated API PR: https://github.com/codeready-toolchain/api/pull/400

2024-02-26 23:20 UTC, alexeykazakov approved these changes

2024-02-27 09:30 UTC, mfrancisc approved these changes

2024-02-28 23:52 UTC, alexeykazakov commented on pkg/configuration/configuration.go
> -	return commonconfig.GetString(r.c.AuthClientPublicKeysURL, "https://sso.devsandbox.dev/auth/realms/sandbox-dev/protocol/openid-connect/certs")
Is it a new keycloak thing? Or specific to our dev sso configuration?
We do rely on `auth/realms` path in a few places which is consistent with our production sso.redhat.com.
If we have a different path in dev sso then it won't work OOTB.
See https://github.com/search?q=repo%3Acodeready-toolchain%2Fregistration-service+%22auth%2Frealms%22&type=code

2024-02-28 23:53 UTC, alexeykazakov requested changes
Please see my comment above regarding the "auth/realm" path.

2024-02-29 03:50 UTC, alexeykazakov approved these changes

2024-02-29 05:27 UTC, merged